version: "3.9"
services:
  node:
    build: .
    ports:
      - '4000:3004'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./.env

  rabit:
    image: rabbitmq
    ports:
      - "5672:5672"
      - 15672:15672
